#: import menu menu

MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "images/bg1.jpg"  # background image

    menu_widget:menu_widget  # permet assigner objet vers .py
    # lie a variable perspective_point_x du .py
    perspective_point_x: self.width / 2
    perspective_point_y: self.height * 0.75
    MenuWidget:
        id: menu_widget